sudo: 
  false

language: 
  c 


services:
  - docker

before_install:
  - export ACCOUNT=ocramz

script:
  # # build Docker image
  - make build ACCOUNTNAME=$ACCOUNT

  # - docker push $ACCOUNT/petsc-docker

  # - git clone https://github.com/ocramz/petsc-hs.git
  # - cd petsc-hs
  # - make


# addons:
#   apt:
#     packages:
#     - gfortran            # needed to build PETSc
#     - libgmp-dev          # needed by GHC