sudo: 
  true

language: 
  c 

services:
  # - docker

before_install:
  # - sudo service docker stop
  # - curl -fsSL https://get.docker.com/ | sudo sh
  # - sudo usermod -aG docker root
  # # - sudo service docker start
  # - ps -A | grep docker
  # - sudo docker -d
  - sudo echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" >> /etc/apt/sources.list.d/docker.list
  - sudo apt-get update
  - sudo apt-get install docker-engine
  

env:
  global:
    - ACCOUNT=ocramz
    - PROJECT=petsc-docker
    - TAG=$ACCOUNT/$PROJECT
  matrix:
    - BATCH_MODE="batch"
    - BATCH_MODE=""

script:
  # # build Docker image
  - docker build -t $TAG --build-arg BUILDTYPE=$BATCH_MODE .