sudo: 
  false

language: 
  c 


services:
  - docker

script:
  - make build ACCOUNTNAME=ocramz
  - git clone https://github.com/ocramz/petsc-hs.git
  - cd petsc-hs
  - make


# addons:
#   apt:
#     packages:
#     - gfortran            # needed to build PETSc
#     - libgmp-dev          # needed by GHC