sudo: 
  true

language: 
  c 

services:
  # - docker

before_install:
  - curl -fsSL https://get.docker.com/ | sudo sh
  - sudo service docker start

env:
  global:
    - ACCOUNT=ocramz
    - PROJECT=petsc-docker
    - TAG=$ACCOUNT/$PROJECT
  matrix:
    - BATCH_MODE="batch"
    - BATCH_MODE=""

script:
  # # build Docker image
  - docker build -t $TAG --build-arg BUILDTYPE=$BATCH_MODE .