sudo: 
  false

language: 
  c 

services:
  - docker

before_install:

env:
  global:
    - ACCOUNT=ocramz
    - PROJECT=petsc-docker
    - TAG=$ACCOUNT/$PROJECT
  matrix:
    - BATCH_MODE="batch"
    - BATCH_MODE=""

script:
  # # build Docker image
  - docker build -t $TAG --build-arg BUILDTYPE=$BATCH_MODE .