sudo: 
  false

language: 
  c 


services:
  - docker

script:
  # # build petsc-docker image
  - make build ACCOUNTNAME=ocramz

  # - git clone https://github.com/ocramz/petsc-hs.git
  # - cd petsc-hs
  # - make


# addons:
#   apt:
#     packages:
#     - gfortran            # needed to build PETSc
#     - libgmp-dev          # needed by GHC