sudo: 
  required

language: 
  c 

services:
  - docker

# addons:
#   apt:
#     packages:
#     - docker-engine

before_install:
  - sudo apt-get install slurm-llnl

env:
  global:
    - ACCOUNT=ocramz
    - PROJECT=petsc-docker
    - IMAGE_NAME=${ACCOUNT}/${PROJECT}-batch


script:
  # # build Docker image
  # - docker build -t ${TAG} -f Dockerfile .
  - docker build -t ${IMAGE_NAME} -f Dockerfile-batch .

  # run image, copy file from designated master node to compute node
  - docker run --rm -it --name "master"  ${IMAGE_NAME}
  - docker run --rm -it --name "compute" ${IMAGE_NAME}
  