sudo: 
  false

language: 
  c 

services:
  - docker

# addons:
#   apt:
#     packages:
#     - docker-engine

before_install:

env:
  global:
    - ACCOUNT=ocramz
    - PROJECT=petsc-docker
    - IMAGE_NAME=${ACCOUNT}:${PROJECT}

script:
  # # build Docker image
  # - docker build -t ${TAG} -f Dockerfile .
  - docker build -t ${IMAGE_NAME}-batch -f Dockerfile-batch .

  # run image, copy file from designated master node to compute node
  - docker run --rm -it --name "master" ${IMAGE_NAME}-batch
  - docker run --rm -it --name "compute" ${IMAGE_NAME}-batch
  